export type QuoteRequestInput = {
  name: string;
  company: string | null;
  email: string;
  phone: string | null;
  location: string | null;
  product: string | null;
  quantity: number | null;
  quantityUnit: string | null;
  installation: string | null;
  timeline: string | null;
  message: string | null;
  drawing: { name: string; contentBase64: string; contentType: string } | null;
};

const BUCKET = "quote-drawings";

/** GVT-YYMM-#### reference numbers are generated by the database sequence. */
async function nextReference(client: {
  rpc: (fn: string) => Promise<{ data: unknown; error: { message: string } | null }>;
}) {
  const { data, error } = await client.rpc("next_gvt_reference");
  if (error) throw new Error(error.message);
  return String(data);
}

export async function saveQuoteRequest(input: QuoteRequestInput) {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

  const reference = await nextReference(
    supabaseAdmin as unknown as Parameters<typeof nextReference>[0],
  );

  let drawingPath: string | null = null;
  if (input.drawing) {
    const safeName = input.drawing.name.replace(/[^\w.\-]+/g, "_").slice(-80);
    const path = `${reference}/${safeName}`;
    const bytes = Uint8Array.from(atob(input.drawing.contentBase64), (c) => c.charCodeAt(0));
    const { error } = await supabaseAdmin.storage
      .from(BUCKET)
      .upload(path, bytes, { contentType: input.drawing.contentType, upsert: true });
    if (!error) drawingPath = path;
    else console.error("[quote] drawing upload failed:", error.message);
  }

  const { data, error } = await supabaseAdmin
    .from("quote_requests")
    .insert({
      reference,
      name: input.name,
      company: input.company,
      email: input.email,
      phone: input.phone,
      location: input.location,
      product: input.product,
      quantity: input.quantity,
      quantity_unit: input.quantityUnit,
      installation: input.installation,
      timeline: input.timeline,
      message: input.message,
      drawing_path: drawingPath,
    })
    .select("id, reference")
    .single();

  if (error) throw new Error(error.message);

  return { id: data.id as string, reference: (data.reference as string) ?? reference };
}
