/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as PaymentSecurityRouteImport } from './routes/payment-security'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ReturnPolicyRouteImport } from './routes/return-policy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiPublicSnippeWebhookRouteImport } from './routes/api/public/snippe-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSecurityRoute = PaymentSecurityRouteImport.update({
  id: '/payment-security',
  path: '/payment-security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnPolicyRoute = ReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSnippeWebhookRoute = ApiPublicSnippeWebhookRouteImport.update({
  id: '/api/public/snippe-webhook',
  path: '/api/public/snippe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/donate': typeof DonateRoute
  '/payment-security': typeof PaymentSecurityRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/shop': typeof ShopRoute
  '/success': typeof SuccessRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/snippe-webhook': typeof ApiPublicSnippeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/donate': typeof DonateRoute
  '/payment-security': typeof PaymentSecurityRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/shop': typeof ShopRoute
  '/success': typeof SuccessRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/snippe-webhook': typeof ApiPublicSnippeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/donate': typeof DonateRoute
  '/payment-security': typeof PaymentSecurityRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/shop': typeof ShopRoute
  '/success': typeof SuccessRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/snippe-webhook': typeof ApiPublicSnippeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/cookie-policy'
    | '/donate'
    | '/payment-security'
    | '/privacy-policy'
    | '/return-policy'
    | '/shop'
    | '/success'
    | '/sustainability'
    | '/terms-and-conditions'
    | '/product/$slug'
    | '/api/public/snippe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/cookie-policy'
    | '/donate'
    | '/payment-security'
    | '/privacy-policy'
    | '/return-policy'
    | '/shop'
    | '/success'
    | '/sustainability'
    | '/terms-and-conditions'
    | '/product/$slug'
    | '/api/public/snippe-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/cookie-policy'
    | '/donate'
    | '/payment-security'
    | '/privacy-policy'
    | '/return-policy'
    | '/shop'
    | '/success'
    | '/sustainability'
    | '/terms-and-conditions'
    | '/product/$slug'
    | '/api/public/snippe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DonateRoute: typeof DonateRoute
  PaymentSecurityRoute: typeof PaymentSecurityRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReturnPolicyRoute: typeof ReturnPolicyRoute
  ShopRoute: typeof ShopRoute
  SuccessRoute: typeof SuccessRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicSnippeWebhookRoute: typeof ApiPublicSnippeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-security': {
      id: '/payment-security'
      path: '/payment-security'
      fullPath: '/payment-security'
      preLoaderRoute: typeof PaymentSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-policy': {
      id: '/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof ReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/snippe-webhook': {
      id: '/api/public/snippe-webhook'
      path: '/api/public/snippe-webhook'
      fullPath: '/api/public/snippe-webhook'
      preLoaderRoute: typeof ApiPublicSnippeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DonateRoute: DonateRoute,
  PaymentSecurityRoute: PaymentSecurityRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReturnPolicyRoute: ReturnPolicyRoute,
  ShopRoute: ShopRoute,
  SuccessRoute: SuccessRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicSnippeWebhookRoute: ApiPublicSnippeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
