/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OrderStatusRouteImport } from './routes/order-status'
import { Route as OurImpactRouteImport } from './routes/our-impact'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as PaymentSecurityRouteImport } from './routes/payment-security'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ReturnPolicyRouteImport } from './routes/return-policy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicSnippeWebhookRouteImport } from './routes/api/public/snippe-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderStatusRoute = OrderStatusRouteImport.update({
  id: '/order-status',
  path: '/order-status',
  getParentRoute: () => rootRouteImport,
} as any)
const OurImpactRoute = OurImpactRouteImport.update({
  id: '/our-impact',
  path: '/our-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSecurityRoute = PaymentSecurityRouteImport.update({
  id: '/payment-security',
  path: '/payment-security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnPolicyRoute = ReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSnippeWebhookRoute = ApiPublicSnippeWebhookRouteImport.update({
  id: '/api/public/snippe-webhook',
  path: '/api/public/snippe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/mcp': typeof McpRoute
  '/order-status': typeof OrderStatusRoute
  '/our-impact': typeof OurImpactRoute
  '/our-work': typeof OurWorkRoute
  '/payment-security': typeof PaymentSecurityRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/shop': typeof ShopRoute
  '/success': typeof SuccessRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/product/$slug': typeof ProductSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/snippe-webhook': typeof ApiPublicSnippeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/mcp': typeof McpRoute
  '/order-status': typeof OrderStatusRoute
  '/our-impact': typeof OurImpactRoute
  '/our-work': typeof OurWorkRoute
  '/payment-security': typeof PaymentSecurityRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/shop': typeof ShopRoute
  '/success': typeof SuccessRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/product/$slug': typeof ProductSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/snippe-webhook': typeof ApiPublicSnippeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/mcp': typeof McpRoute
  '/order-status': typeof OrderStatusRoute
  '/our-impact': typeof OurImpactRoute
  '/our-work': typeof OurWorkRoute
  '/payment-security': typeof PaymentSecurityRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/shop': typeof ShopRoute
  '/success': typeof SuccessRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/product/$slug': typeof ProductSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/snippe-webhook': typeof ApiPublicSnippeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/cookie-policy'
    | '/mcp'
    | '/order-status'
    | '/our-impact'
    | '/our-work'
    | '/payment-security'
    | '/privacy-policy'
    | '/quote'
    | '/return-policy'
    | '/shop'
    | '/success'
    | '/sustainability'
    | '/terms-and-conditions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/product/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/snippe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/cookie-policy'
    | '/mcp'
    | '/order-status'
    | '/our-impact'
    | '/our-work'
    | '/payment-security'
    | '/privacy-policy'
    | '/quote'
    | '/return-policy'
    | '/shop'
    | '/success'
    | '/sustainability'
    | '/terms-and-conditions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/product/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/snippe-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/cookie-policy'
    | '/mcp'
    | '/order-status'
    | '/our-impact'
    | '/our-work'
    | '/payment-security'
    | '/privacy-policy'
    | '/quote'
    | '/return-policy'
    | '/shop'
    | '/success'
    | '/sustainability'
    | '/terms-and-conditions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/product/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/snippe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  McpRoute: typeof McpRoute
  OrderStatusRoute: typeof OrderStatusRoute
  OurImpactRoute: typeof OurImpactRoute
  OurWorkRoute: typeof OurWorkRoute
  PaymentSecurityRoute: typeof PaymentSecurityRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QuoteRoute: typeof QuoteRoute
  ReturnPolicyRoute: typeof ReturnPolicyRoute
  ShopRoute: typeof ShopRoute
  SuccessRoute: typeof SuccessRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProductSlugRoute: typeof ProductSlugRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicSnippeWebhookRoute: typeof ApiPublicSnippeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-status': {
      id: '/order-status'
      path: '/order-status'
      fullPath: '/order-status'
      preLoaderRoute: typeof OrderStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-impact': {
      id: '/our-impact'
      path: '/our-impact'
      fullPath: '/our-impact'
      preLoaderRoute: typeof OurImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-security': {
      id: '/payment-security'
      path: '/payment-security'
      fullPath: '/payment-security'
      preLoaderRoute: typeof PaymentSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-policy': {
      id: '/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof ReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/snippe-webhook': {
      id: '/api/public/snippe-webhook'
      path: '/api/public/snippe-webhook'
      fullPath: '/api/public/snippe-webhook'
      preLoaderRoute: typeof ApiPublicSnippeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  McpRoute: McpRoute,
  OrderStatusRoute: OrderStatusRoute,
  OurImpactRoute: OurImpactRoute,
  OurWorkRoute: OurWorkRoute,
  PaymentSecurityRoute: PaymentSecurityRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QuoteRoute: QuoteRoute,
  ReturnPolicyRoute: ReturnPolicyRoute,
  ShopRoute: ShopRoute,
  SuccessRoute: SuccessRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProductSlugRoute: ProductSlugRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicSnippeWebhookRoute: ApiPublicSnippeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
